name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Python Script
        uses: jannekem/run-python-script-action@v1.2

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Run Python Script
        uses: jannekem/run-python-script-action@v1.2
        with:
          script: |
            import sys
            import hashlib
            BUF_SIZE = 65536

            files = ["BarberousseRS-", "BarberousseRS", "BarberousseRS+"]
            
            for i in range(len(files)):
              sha1 = hashlib.sha1()
              
              with open("%s/%s.zip" % ("${{ github.workspace }}/",files[i]), 'rb') as f:
                  while True:
                      data = f.read(BUF_SIZE)
                      if not data:
                          break
                      sha1.update(data)
                      
              print(i, " - SHA1: {0}".format(sha1.hexdigest()))
              
              with open("%s/%s.hash" % ("${{ github.workspace }}/",files[i]), 'w') as f:
                f.write("{0}".format(sha1.hexdigest()))
                
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "update hashs"
          git push
