name: CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Python Script
        uses: jannekem/run-python-script-action@v1.2

      - name: Test
        run: ls -l ${{ github.workspace }}

      
