name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Python Script
        uses: jannekem/run-python-script-action@v1.2

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Run Python Script
        uses: jannekem/run-python-script-action@v1.2
        with:
          script: |
            import sys
            import hashlib
            BUF_SIZE = 65536

            md5 = hashlib.md5()
            sha1 = hashlib.sha1()

            with open("${{ github.workspace }}/BarberousseRS+.zip", 'rb') as f:
                while True:
                    data = f.read(BUF_SIZE)
                    if not data:
                        break
                    md5.update(data)
                    sha1.update(data)

            print("MD5: {0}".format(md5.hexdigest()))
            print("SHA1: {0}".format(sha1.hexdigest()))
