name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Python Script
        uses: jannekem/run-python-script-action@v1.2

      - name: Test
        run: |
          ls -l ${{ github.workspace }}

      
